//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class PasswordOption
    {
        public int ID { get; set; }
        public Nullable<bool> AllowLowercaseCharacters { get; set; }
        public Nullable<bool> AllowUppercaseCharacters { get; set; }
        public Nullable<bool> AllowNumberCharacters { get; set; }
        public Nullable<bool> AllowSpecialCharacters { get; set; }
        public Nullable<bool> AllowUnderscoreCharacters { get; set; }
        public Nullable<bool> AllowSpaceCharacters { get; set; }
        public Nullable<bool> AllowOtherCharacters { get; set; }
        public Nullable<bool> RequireLowercaseCharacters { get; set; }
        public Nullable<bool> RequireUppercaseCharacters { get; set; }
        public Nullable<bool> RequireNumberCharacters { get; set; }
        public Nullable<bool> RequireSpecialCharacters { get; set; }
        public Nullable<bool> RequireUnderscoreCharacters { get; set; }
        public Nullable<bool> RequireSpaceCharacters { get; set; }
        public Nullable<bool> RequireOtherCharacters { get; set; }
        public Nullable<int> MinimumCharacters { get; set; }
        public Nullable<int> MaximumCharacters { get; set; }
        public string OtherCharacters { get; set; }
    }
}
