//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public string DateTimeFormat { get; set; }
        public int PasswordOptionsID { get; set; }
        public bool ShowEmailColumn { get; set; }
        public bool ShowUsernameColumn { get; set; }
        public bool ShowPasswordColumn { get; set; }
    }
}
